name: Docker build and push

on:
  push:
    branches: [ "main" ]
    paths:
        - 'app/**'
  pull_request:
    branches: [ "main" ]
    paths:
        - 'app/**'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Assign the timestamp to a variable
      - name: Set timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"

      # Build the Docker image and tag it with the UTC timestamp and latest
      - name: Build the Docker image
        run: |
          docker build . \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/k8s-fastapi:${{ steps.timestamp.outputs.timestamp }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/k8s-fastapi:latest \
            --rm

      # Log in to Docker Hub using the GitHub token
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/k8s-fastapi:${{ steps.timestamp.outputs.timestamp }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/k8s-fastapi:latest